### ISSUE TITLE
https://kernel-panik.me/tool/kprm/ is down

### ISSUE THREAD

**Issue by ave9858** [KernelPan1k/KpRm#10]
https://web.archive.org/web/20230000000000*/https://kernel-panik.me/tool/kprm/ shows it has been down for a while. `curl https://kernel-panik.me/tool/kprm/` gives the error `curl: (35) Recv failure: Connection was reset`.

**Comment by KernelPan1k** [comment]
hello I deleted the site because it was not so interesting and I did not want to maintain it.
-------- Message d'origine --------
