### ISSUE TITLE
ESET Online Scanner Shortcut isn't removed.

### ISSUE THREAD

**Issue by ave9858** [KernelPan1k/KpRm#6]
By default, the ESET online scanner creates a shortcut in `%APPDATA%\Microsoft\Windows\Start Menu\Programs`. This shortcut is not removed, although the scanner itself is.

**Comment by KernelPan1k** [comment]
Hello, thank you for bringing this information up. Do you have the possibility to make a pull request by chance ?

**Comment by ave9858** [comment]
I've never written autoit code before and I'm not sure exactly how the program works, but I'll take a look.

**Comment by KernelPan1k** [comment]
If you can/want otherwise I will

**Comment by ave9858** [comment]
Not sure the best approach, as ESET creates a shortcut in the local start menu, which no other tool seems to do. I could hardcode the local start menu path in tools.xml, or I could add a <startMenuLocal> tag that currently would only be used by ESET Online Scanner. I could also adjust the behavior startMenu tag. I wasn't able to find any other program that made start menu entries, GibonDecrypter was portable in all the downloads I found and I can't find any download for FixPurge.

**Comment by ave9858** [comment]
For testing, I added `<startMenu companyName="" pattern="(?i)^ESET Online Scanner\.lnk$" type="file"/>` and modified the behavior of startMenu to use AppDataDir, which works, but removes the ability to clean the global start menu.
